using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace MinutesGame.Common.SE
{
    /// <summary>
    /// SEデータベースエディタークラス(開発中)
    /// </summary>
    [CustomEditor(typeof(SEDatabase))]
    public class SEDatabaseEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();

            EditorGUILayout.Space();
            if (GUILayout.Button("Generate SE Enum", GUILayout.Height(30)))
            {
                GenerateEnum((SEDatabase)target);
            }
        }

        private void GenerateEnum(SEDatabase database)
        {
            // 保存先の設定（SEDatabaseが定義されているスクリプトと同じフォルダ）
            string assetPath = AssetDatabase.GetAssetPath(MonoScript.FromScriptableObject(database));
            string directory = Path.GetDirectoryName(assetPath);
            string outputPath = Path.Combine(directory, "SEName.cs");

            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// このコードはツールによって生成されました。");
            sb.AppendLine("// 手動で変更すると、再生成時に上書きされます。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace MinutesGame.Common.SE");
            sb.AppendLine("{");
            sb.AppendLine("    public enum SEName");
            sb.AppendLine("    {");

            if (database.SEData != null)
            {
                foreach (var data in database.SEData)
                {
                    if (string.IsNullOrEmpty(data.SEName)) continue;

                    // C#の変数名として使えない文字をアンダースコアに置換
                    string safeName = Regex.Replace(data.SEName, @"[^a-zA-Z0-9_]", "_");

                    // 先頭が数字の場合はアンダースコアを付与
                    if (Regex.IsMatch(safeName, @"^[0-9]"))
                    {
                        safeName = "_" + safeName;
                    }

                    sb.AppendLine($"        {safeName},");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            Debug.Log($"<color=cyan><b>[SEDatabase]</b></color> Enum generated at: {outputPath}");
        }
    }
}
