// <auto-generated>
// このコードはツールによって生成されました。
// 手動で変更すると、再生成時に上書きされます。
// </auto-generated>

namespace MinutesGame.Common.SE
{
    public enum SEName
    {
        Correct,
        Incorrect,
    }
}
